package lib.globals;

public enum Stage {
	
//WILDERNESS AGILITY
	WILDERNESS_AGILITY_PIPE,
	WILDERNESS_AGILITY_ROPE,
	WILDERNESS_AGILITY_ESCAPE_FALL,
	WILDERNESS_AGILITY_STONES,
	WILDERNESS_AGILITY_LOG,
	WILDERNESS_AGILITY_ROCK_CLIMB,
	WILDERNESS_AGILITY_EAT
	
}
